version: "3.7"
services:

  redis:
    image: redis:5.0.4-alpine
    ports:
      - "6379"
    networks:
      - backplane
    volumes:
       - ./redis-data:/data      

  redis-worker:
    build: ./worker
    networks:
      - backplane
    depends_on:
      - "redis"
    environment:
      - REDIS_HOSTNAME=redis

networks:
  backplane:
